import {
  Android,
  ArrowRight,
  Brush,
  Briefcase,
  Bug,
  Calendar,
  Check,
  Code,
  Copy,
  Crown,
  Database,
  Eye,
  Flag,
  GitBranch,
  GitMerge,
  Github,
  Globe,
  Home,
  Close,
  Lock,
  Mail,
  Menu,
  Monitor,
  Moon,
  Mouse,
  Pencil,
  Phone,
  Play,
  Shield,
  Sparkles,
  Sun,
  User,
} from "pixelarticons/react";

// One icon family for the whole site: Pixelarticons (MIT).
const ICONS = {
  android: Android,
  "arrow-right": ArrowRight,
  briefcase: Briefcase,
  brush: Brush,
  bug: Bug,
  calendar: Calendar,
  check: Check,
  code: Code,
  copy: Copy,
  crown: Crown,
  database: Database,
  eye: Eye,
  flag: Flag,
  "git-branch": GitBranch,
  "git-merge": GitMerge,
  github: Github,
  globe: Globe,
  home: Home,
  close: Close,
  lock: Lock,
  mail: Mail,
  menu: Menu,
  monitor: Monitor,
  moon: Moon,
  mouse: Mouse,
  pencil: Pencil,
  phone: Phone,
  play: Play,
  shield: Shield,
  sparkles: Sparkles,
  sun: Sun,
  user: User,
} as const;

export type IconName = keyof typeof ICONS;

export function Icon({ name, className = "size-6" }: { name: IconName | string; className?: string }) {
  const Svg = ICONS[name as IconName];
  if (!Svg) return null;
  return <Svg aria-hidden="true" focusable="false" className={className} />;
}
